version: '3'

services:

  mysql:
    image: mysql:8
    container_name: payments_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
    ports:
      - "3306:3306"

  gateway-mock:
    image: matheusprotzen/gateways-mock
    ports:
      - "3001:3001"
      - "3002:3002"